pref("extensions.fullscreen.on", true);
pref("extensions.fullscreen.version", 100);
pref("extensions.fullscreen.on_fullscreen", false);
pref("extensions.fullscreen.mouse_button", 2);
pref("extensions.fullscreen.menubar", true);
pref("extensions.fullscreen.navbar", true);
pref("extensions.fullscreen.bookmarbar", true);
pref("extensions.fullscreen.addonbar", true);
pref("extensions.fullscreen.bottom_trigger", true);
